### ISSUE TITLE
Замечания по lw2

### ISSUE THREAD

**Issue by ivklgn** [sweetjes/videogallery#1]
**Task3**
1. `slider1` - непонятно почему 1, лучше назвать name="youtube-iframe"

**Comment by ivklgn** [comment]
**Task4**
1. `.com`, `f_c` - называйте классы полными словами, понятно
2. стилизация должна быть на классах

```css
input[type="text"] {
  width: 915px;
  border: 1px solid black;
  line-height: 40px;
  padding: 5px;
  color: black;
}

input::-webkit-input-placeholder {
  color: black;
}

textarea {
  width: 915px;
  color: black;
  border: 1px solid black;
  resize: none;
  padding: 5px;
}
```
